### ISSUE TITLE
FPL_MEGABYTES, FPL_GIGABYTES, FPL_TERABYTES macros are incorrect

### ISSUE THREAD

**Issue by kevinmoran** [f1nalspace/final_game_tech#1]
https://github.com/f1nalspace/final_game_tech/blob/037a51ab1502d1ff928d9ba60d9bf690a1f1f39f/final_platform_layer.hpp#L423

Just spotted a small typo bug while browsing through the source.

`#define FPL_MEGABYTES(value) (FPL_KILOBYTES() * 1024)
`
should be:

`#define FPL_MEGABYTES(value) (FPL_KILOBYTES(value) * 1024)
`

and similar for FPL_GIGABYTES, FPL_TERABYTES.

**Comment by f1nalspace** [comment]
I fixed it in v0.4.1 alpha
