### ISSUE TITLE
Incorrect initial window background color on windows

### ISSUE THREAD

**Issue by khvorov45** [f1nalspace/final_game_tech#127]
Windows 10 tends to create windows with a white background by default (on window creation, before the program had a chance to draw anything itself). 

The default background can be set on the window class as you are doing here

https://github.com/f1nalspace/final_game_tech/blob/33b63dc0664e16682d4298371f3166869c233b0f/final_platform_layer.h#L11472

I'm not sure what `COLOR_WINDOW + 1` is supposed to correspond to (it's 5 + 1, so it's `COLOR_WINDOWFRAME` I guess, maybe `COLOR_BACKGROUND` would be more appropriate?) but it appears to also be a white color unless you enable the "high contrast" mode in windows with a dark background in which case it's black.

Whatever that color is, windows seems to ignore it when you create a window without the `WS_VISIBLE` flag. 

If I set the color to red

```c
windowClass.hbrBackground = CreateSolidBrush(RGB(255,0,0));
```

then the initial window should presumably be red but it's still white.

I found that showing the window like this on startup

```c
wapi->user.ShowWindow(windowState->windowHandle, SW_SHOWMINIMIZED);
wapi->user.ShowWindow(windowState->windowHandle, SW_SHOWNORMAL);
```

Creates the window with the expected color. (As does creating it with the `WS_VISIBLE` flag set but it still seems to flash white briefly right after the `CreateWindowExW` call unless you actually `CreateSolidBrush` instead of casting).

I don't know if there is a better solution than that. I care about this because you have to launch and relaunch the program a lot in development and I don't want to be flashbanged every time.

Test program I used for this:

```c
#define FPL_IMPLEMENTATION
#define FPL_NO_ENTRYPOINT
#include "final_platform_layer.h"

int CALLBACK WinMain(HINSTANCE Instance, HINSTANCE PrevInstance, LPSTR CommandLine, int ShowCode) {
    fplSettings settings = fplMakeDefaultSettings();
    settings.video.backend = fplVideoBackendType_Software;
    if (fplPlatformInit(fplInitFlags_Video, &settings)) {
        while (fplWindowUpdate()) {
            fplEvent ev;
            while (fplPollEvent(&ev)) {}
            fplVideoFlip();
        }
        fplPlatformRelease();
        return 0;
    } else {
        return -1;
    }
}
```

**Comment by f1nalspace** [comment]
Thanks for finding the issue. I made a simple change, can you please check out the branch and report me back if that solves the issue?

https://github.com/f1nalspace/final_game_tech/tree/bugfix/127-incorrect-default-window-color

**Comment by khvorov45** [comment]
No, it's still the same. White background on creation. Black background if I add the `WS_VISIBLE` flag to `CreateWindowExW` or do the show minimised - show normal dance.

I see you are setting the background differently now. Maybe it's more to do with some set of messages that aren't sent when the window is created without `WS_VISIBLE` (and `ShowWindow` doesn't send them either I guess).

You'd think `ShowWindow` after `CreateWindow` without `WS_VISIBLE` would be the same as `CreateWindow` with `WS_VISIBLE`

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexw
>If an overlapped window is created with the WS_VISIBLE style bit set and the x parameter is set to CW_USEDEFAULT, then the y parameter determines how the window is shown. If the y parameter is CW_USEDEFAULT, then the window manager calls ShowWindow with the SW_SHOW flag after the window has been created. If the y parameter is some other value, then the window manager calls ShowWindow with that value as the nCmdShow parameter.

But I guess not

**Comment by khvorov45** [comment]
I think I found the culprit

https://github.com/f1nalspace/final_game_tech/blob/ef84599a07217029fd77f4b91cf26e5cc2af6fab/final_platform_layer.h#L11455-L11461

The background is filled with the brush on getting the `WM_ERASEBKGND` message.

https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-erasebkgnd
>The DefWindowProc function erases the background by using the class background brush specified by the hbrBackground member of the WNDCLASS structure. If hbrBackground is NULL, the application should process the WM_ERASEBKGND message and erase the background.

If you ignore that message on startup then the window just fills with the default color.

If I comment out that `return 1` effectively passing the message to `DefWindowProc` then the initial color is black with the software backend, as expected.

This also explains why the window flashes white briefly upon showing up - it is shown before the `WM_ERASEBKGND` is sent (can see that happen if you set the breakpoint inside `fpl__Win32MessageProc`).

I also tested what happens on show minimised/show normal - the window is also shown before `WM_ERASEBKGND` but it actually has the correct color already by that point. Not sure what the reason for that is, presumably it's one of the messages sent on show minimised.

So if there a way to convince windows to erase the background of a not-yet-shown window then that will solve the problem of the default background of a non-none video backend and the problem of flashing white on appearance.

**Comment by f1nalspace** [comment]
> I think I found the culprit
> 
> https://github.com/f1nalspace/final_game_tech/blob/ef84599a07217029fd77f4b91cf26e5cc2af6fab/final_platform_layer.h#L11455-L11461
> 
> The background is filled with the brush on getting the `WM_ERASEBKGND` message.
> 
> https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-erasebkgnd
> 
> > The DefWindowProc function erases the background by using the class background brush specified by the hbrBackground member of the WNDCLASS structure. If hbrBackground is NULL, the application should process the WM_ERASEBKGND message and erase the background.
> 
> If you ignore that message on startup then the window just fills with the default color.
> 
> If I comment out that `return 1` effectively passing the message to `DefWindowProc` then the initial color is black with the software backend, as expected.
> 
> This also explains why the window flashes white briefly upon showing up - it is shown before the `WM_ERASEBKGND` is sent (can see that happen if you set the breakpoint inside `fpl__Win32MessageProc`).
> 
> I also tested what happens on show minimised/show normal - the window is also shown before `WM_ERASEBKGND` but it actually has the correct color already by that point. Not sure what the reason for that is, presumably it's one of the messages sent on show minimised.
> 
> So if there a way to convince windows to erase the background of a not-yet-shown window then that will solve the problem of the default background of a non-none video backend and the problem of flashing white on appearance.

Sorry for the late reply, but i am very busy at the moment so i apologize for that.

Regarding that issue, so if i simply let windows do the erasing of the window for software output the problem is fixed right? If that is so, then i will do that ;-)

**Comment by khvorov45** [comment]
>Regarding that issue, so if i simply let windows do the erasing of the window for software output the problem is fixed right? If that is so, then i will do that ;-)

That works, thanks.

**Comment by roytam1** [comment]
> Thanks for the hint, but I already solved the issue (https://github.com/f1nalspace/final_game_tech/blob/develop/final_platform_layer.h#L11680) by simply using GetSysColorBrush(COLOR_WINDOW).

I knew this and I left a comment about this because I was redirected to here by google search result and I think that comment may help others as well. :)
