### ISSUE TITLE
error when compiling with g++ 10.2.1-6 or clang++ 11

### ISSUE THREAD

**Issue by mladinox** [f1nalspace/final_game_tech#158]
./final_platform_layer.h:2297:51: error: no match for ‘operator=’ (operand types are ‘fplVersionInfo’ and ‘<brace-enclosed initializer list>’)
 2297 | # define fpl__m_StructInit(type, ...) {__VA_ARGS__}

**Comment by f1nalspace** [comment]
Please double-check if the compile error happens on the main branch and report back. Thanks!

**Comment by f1nalspace** [comment]
Closed due to duplicate of #161
