### ISSUE TITLE
windows specific virtual keys in keyboard events

### ISSUE THREAD

**Issue by tomaszte** [f1nalspace/final_game_tech#6]
Hi,
when I press i.e. '.' (COMMA) and I fetch the fplEvent then 
keyCode is 190
mappedKey is fplKey_None

190 is id of VK_OEM_COMMA in https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
shouldn't windows virtualKeys be mapped to ascii?

Regards

**Comment by f1nalspace** [comment]
Ah thanks i will double check and fix that.

**Comment by f1nalspace** [comment]
Its implemented in v0.8.2.0, so i will close the issue.
